[package]
name = "windowed_iterator"
description = "An implementation of a sliding window iterator adapter."
version = "0.1.0"
authors = ["Severen Redwood <severen@shrike.me>"]
license = "MPL-2.0"

edition = "2018"

[dependencies]

[dev-dependencies]
proptest = "0.9.3"
